language: php
php:
  - 7.4

# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  ## Fetch data from testrail
  - cd scripts/
  - composer install
  - cd ../
  - php scripts/bin/console testrail:export:data
  ## Hugo
  - ./bin/installHugo.sh
  - cd src
  - ../hugo
  - cd ../

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: src/public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  verbose: true
  on:
    branch: master

after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git checkout master
  - git add -f src/content/tests/modules
  - git commit -m "Travis Update (Build $TRAVIS_BUILD_NUMBER)" -m "[skip ci]"
  # Remove existing "origin"
  - git remote rm origin
  # Add new "origin" with access token in the git URL for authentication
  - git remote add origin https://Progi1984:${GITHUB_TOKEN}@github.com/PrestaShop/test-scenarios.git > /dev/null 2>&1
  - git push origin master --quiet
