baseURL: "https://build.prestashop.com/test-scenarios/"
languageCode: "en-us"
defaultContentLanguage: "en"
title: "PrestaShop Tests"

theme: "hugo-geekdoc"

params:
  geekdocBreadcrumb: true
  geekdocLogo: "logo.png"
  geekdocRepo: "https://github.com/PrestaShop/test-scenarios"
  geekdocSearch: true
  geekdocSearchShowParent: true
  geekdocMenuBundle: false

markup:
  goldmark:
    renderer:
      unsafe: true