baseURL: "https://progi1984.github.io/prestashop-tests/"
languageCode: "en-us"
defaultContentLanguage: "en"
title: "PrestaShop Tests"

theme: "hugo-geekdoc"

params:
  geekdocBreadcrumb: true
  geekdocLogo: "logo.png"
  geekdocRepo: "https://github.com/PrestaShop/test-scenarios"
  geekdocSearch: true
  geekdocSearchShowParent: true
  geekdocMenuBundle: false