name: "Scenarios : Move in project"

on:
  issues:
    types: [ labeled ]

jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to column
        uses: Machine-Maker/add-to-project-action@v0.2.0
        with:
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
          project-url: https://github.com/orgs/PrestaShop/projects/30/views/1
          column-field: Status
          label-to-column-map: |
            {
              "STATE : To Be Automated": "Todo",
              "STATE : Automation in progress": "In Progress",
              "STATE : Automated": "Done"
            }
